security:
    encoders:
        App\ZsVirSoft\SoftGenBundle\Entity\Users: bcrypt

    providers:
        our_db_provider:
            entity:
                class: ZsVirSoftSoftGenBundle:Users
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false      
        login2:
            pattern:  ^/api/mysoft
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/mysoft/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        others:
            pattern: ^/
            anonymous: ~
            
    access_control:
        - { path: ^/downloadCsv, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/mysoft, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
