<?php

namespace App\ZsVirSoft\SoftGenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GentableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GentableRepository extends EntityRepository
{
	public function findFields($user)	
	{
		$em = $this->getEntityManager("soft_gen");
		$query = $em
			->createQuery('
				SELECT g.id, g.namepub, g.name
				FROM ZsVirSoftSoftGenBundle:Gentable g
				WHERE g.users = :users
			')->setParameter('users', $user); 
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

	public function deleteAll($user)	
	{
		$em = $this->getEntityManager("soft_gen");
		$query = $em
			->createQuery('
				DELETE FROM ZsVirSoftSoftGenBundle:Gentable g
					WHERE g.users = :users
			')->setParameter('users', $user); 
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}	
	
}
