<?php

namespace App\ZsVirSoft\SoftGenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
	public function findFields($user)	
	{
		$em = $this->getEntityManager("soft_gen");
		$query = $em
			->createQuery('
				SELECT t.id, t.name
				FROM ZsVirSoftSoftGenBundle:Type t
			'); 
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}	
	
	
}
